-- MySQL Script generated by MySQL Workbench
-- Mon Oct  1 20:30:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema durafa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema durafa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `durafa` DEFAULT CHARACTER SET utf8 ;
USE `durafa` ;

-- -----------------------------------------------------
-- Table `durafa`.`hierarquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`hierarquia` (
  `idhierarquia` INT NOT NULL AUTO_INCREMENT,
  `nivel` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idhierarquia`),
  UNIQUE INDEX `idhierarquia_UNIQUE` (`idhierarquia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`loja` (
  `idloja` INT NOT NULL AUTO_INCREMENT,
  `nome_loja` VARCHAR(45) NOT NULL,
  `ip_loja` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idloja`),
  UNIQUE INDEX `idloja_UNIQUE` (`idloja` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `id_hierarquia` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `id_hierarquia_idx` (`id_hierarquia` ASC) VISIBLE,
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `id_hierarquia`
    FOREIGN KEY (`id_hierarquia`)
    REFERENCES `durafa`.`hierarquia` (`idhierarquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`fornecedor` (
  `idfornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfornecedor`),
  UNIQUE INDEX `idfornecedor_UNIQUE` (`idfornecedor` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `idtipo_UNIQUE` (`idtipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`cor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`cor` (
  `idcor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `hexadec` VARCHAR(45) NULL,
  PRIMARY KEY (`idcor`),
  UNIQUE INDEX `idcor_UNIQUE` (`idcor` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`tamanho` (
  `idtamanho` INT NOT NULL AUTO_INCREMENT,
  `tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtamanho`),
  UNIQUE INDEX `idtamanho_UNIQUE` (`idtamanho` ASC) VISIBLE,
  UNIQUE INDEX `tamanho_UNIQUE` (`tamanho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`referencia` (
  `idreferencia` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(110) NOT NULL,
  PRIMARY KEY (`idreferencia`),
  UNIQUE INDEX `idreferencia_UNIQUE` (`idreferencia` ASC) VISIBLE,
  UNIQUE INDEX `referencia_UNIQUE` (`referencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`estoques` (
  `idestoques` INT NOT NULL AUTO_INCREMENT,
  `nome_estoques` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestoques`),
  UNIQUE INDEX `idestoques_UNIQUE` (`idestoques` ASC) VISIBLE,
  UNIQUE INDEX `nome_estoques_UNIQUE` (`nome_estoques` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `barcode_img` LONGTEXT NULL,
  `barcode_num` BIGINT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `preco_venda` FLOAT NOT NULL,
  `preco_compra` FLOAT NOT NULL,
  `id_estoques_produto` INT NOT NULL,
  `id_referencia_produto` INT NOT NULL,
  `id_tamanho_produto` INT NOT NULL,
  `id_fornecedor_produto` INT NOT NULL,
  `id_tipo_produto` INT NOT NULL,
  `id_cor_produto` INT NOT NULL,
  PRIMARY KEY (`idproduto`),
  UNIQUE INDEX `idproduto_UNIQUE` (`idproduto` ASC) VISIBLE,
  UNIQUE INDEX `barcode_num_UNIQUE` (`barcode_num` ASC) VISIBLE,
  INDEX `id_referencia_produto_idx` (`id_referencia_produto` ASC) VISIBLE,
  INDEX `id_tamanho_produto_idx` (`id_tamanho_produto` ASC) VISIBLE,
  INDEX `id_fornecedor_produto_idx` (`id_fornecedor_produto` ASC) VISIBLE,
  INDEX `id_estoques_produto_idx` (`id_estoques_produto` ASC) VISIBLE,
  INDEX `id_tipo_produto_idx` (`id_tipo_produto` ASC) VISIBLE,
  INDEX `id_cor_produto_idx` (`id_cor_produto` ASC) VISIBLE,
  CONSTRAINT `id_referencia_produto`
    FOREIGN KEY (`id_referencia_produto`)
    REFERENCES `durafa`.`referencia` (`idreferencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tamanho_produto`
    FOREIGN KEY (`id_tamanho_produto`)
    REFERENCES `durafa`.`tamanho` (`idtamanho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_fornecedor_produto`
    FOREIGN KEY (`id_fornecedor_produto`)
    REFERENCES `durafa`.`fornecedor` (`idfornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_estoques_produto`
    FOREIGN KEY (`id_estoques_produto`)
    REFERENCES `durafa`.`estoques` (`idestoques`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tipo_produto`
    FOREIGN KEY (`id_tipo_produto`)
    REFERENCES `durafa`.`tipo` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cor_produto`
    FOREIGN KEY (`id_cor_produto`)
    REFERENCES `durafa`.`cor` (`idcor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`controle_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`controle_estoque` (
  `idcontrole_estoque` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `id_produto_controle` INT NOT NULL,
  PRIMARY KEY (`idcontrole_estoque`),
  UNIQUE INDEX `idcontrole_estoque_UNIQUE` (`idcontrole_estoque` ASC) VISIBLE,
  INDEX `id_produto_idx` (`id_produto_controle` ASC) VISIBLE,
  CONSTRAINT `id_produto_controle`
    FOREIGN KEY (`id_produto_controle`)
    REFERENCES `durafa`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_venda` INT NOT NULL,
  `id_loja_venda` INT NOT NULL,
  `data_venda` VARCHAR(45) NOT NULL,
  `valor_pago` FLOAT NULL,
  `valor_desconto` FLOAT NULL,
  `preco_total_desconto` FLOAT NULL,
  `total` FLOAT NULL,
  `troco` FLOAT NULL,
  `metodo_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idvenda`),
  UNIQUE INDEX `idvenda_UNIQUE` (`idvenda` ASC) VISIBLE,
  INDEX `id_usuario_venda_idx` (`id_usuario_venda` ASC) VISIBLE,
  INDEX `id_loja_venda_idx` (`id_loja_venda` ASC) VISIBLE,
  CONSTRAINT `id_usuario_venda`
    FOREIGN KEY (`id_usuario_venda`)
    REFERENCES `durafa`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_loja_venda`
    FOREIGN KEY (`id_loja_venda`)
    REFERENCES `durafa`.`loja` (`idloja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`itens_venda` (
  `iditens_venda` INT NOT NULL AUTO_INCREMENT,
  `id_produto_itenvenda` INT NOT NULL,
  `id_venda_itenvenda` INT NOT NULL,
  `sub_total_produto` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`iditens_venda`),
  UNIQUE INDEX `iditens_venda_UNIQUE` (`iditens_venda` ASC) VISIBLE,
  INDEX `id_produto_itenvenda_idx` (`id_produto_itenvenda` ASC) VISIBLE,
  INDEX `id_venda_itenvenda_idx` (`id_venda_itenvenda` ASC) VISIBLE,
  CONSTRAINT `id_produto_itenvenda`
    FOREIGN KEY (`id_produto_itenvenda`)
    REFERENCES `durafa`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_venda_itenvenda`
    FOREIGN KEY (`id_venda_itenvenda`)
    REFERENCES `durafa`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durafa`.`item_avulso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durafa`.`item_avulso` (
  `iditem_avulso` INT NOT NULL AUTO_INCREMENT,
  `id_venda_itemavulso` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `sub_total` FLOAT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`iditem_avulso`),
  UNIQUE INDEX `iditem_avulso_UNIQUE` (`iditem_avulso` ASC) VISIBLE,
  INDEX `id_venda_itemavulso_idx` (`id_venda_itemavulso` ASC) VISIBLE,
  CONSTRAINT `id_venda_itemavulso`
    FOREIGN KEY (`id_venda_itemavulso`)
    REFERENCES `durafa`.`venda` (`idvenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `durafa`;

DELIMITER $$
USE `durafa`$$
CREATE TRIGGER t_vende_item AFTER INSERT ON itens_venda FOR EACH ROW
BEGIN
	UPDATE controle_estoque SET quantidade = quantidade - NEW.quantidade WHERE id_produto_controle = NEW.id_produto_itenvenda;
END$$

USE `durafa`$$
CREATE TRIGGER t_volta_item AFTER DELETE ON itens_venda FOR EACH ROW
BEGIN
	UPDATE controle_estoque SET quantidade = quantidade + OLD.quantidade WHERE id_produto_controle = OLD.id_produto_itenvenda;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
